fullnameOverride: ""
alertmanager:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
     - alertmanager.127.0.0.1.nip.io
  service:
    nodePort: 32000
    type: NodePort
prometheus:
  enabled: true
  service:
    nodePort: 30000
    type: NodePort
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.127.0.0.1.nip.io
grafana:
  enabled: true
  forceDeployDashboards: false
  defaultDashboardsEnabled: true
  defaultDashboardsTimezone: utc
  defaultDashboardsEditable: true
  adminPassword: prom-operator
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.127.0.0.1.nip.io
  service:
    nodePort: 31000
    type: NodePort
prometheus-node-exporter:
  service:
    nodePort: 32001
    type: NodePort
