apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argo-cd
spec:
  destination:
    namespace: argo-rollouts
    server: https://kubernetes.default.svc
  project: laptop
  source:
    chart: argo-rollouts
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: v2.34.3
    helm:
      valuesObject:
        fullnameOverride: "argo-rollouts"
        dashboard:
          enabled: true
          ingress:
            hosts: 
            - argo-rollouts.127.0.0.1.nip.io
            enabled: true
            ingressClassName: nginx

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
