apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argo-cd
spec:
  destination:
    namespace: metrics-server
    server: https://kubernetes.default.svc
  project: laptop
  source:
    chart: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: v3.12.0
    helm:
      valuesObject:
        fullnameOverride: "metrics-server"
        args: 
          - --kubelet-insecure-tls

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
