apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vpa-selfsigned-cert
  namespace: kube-system
spec:
  commonName: vpa-webhook.kube-system.svc
  dnsNames:
    - vpa-webhook.kube-system.svc
  secretName: vpa-tls-certs
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
